version: 2
registries:
  nuget-github:
    type: nuget-feed
    url: https://nuget.pkg.github.com/ricado-group/index.json
    token: ${{ secrets.GH_PACKAGES_PAT }}
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Pacific/Auckland"
  
  # Maintain dependencies for NuGet Packages
  - package-ecosystem: "nuget"
    directory: "/"
    registries:
      - nuget-github
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Pacific/Auckland"